apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tpjvbk79l-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tpjvbk79l-python 
  name: tpjvbk79l-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tpjvbk79l-python 
